// Catálogos maestros de SAP Business One (SIAMO) para la carga de órdenes de compra.
//
// Fuente: archivo "INFORMACION PARA CAMILO.xlsx" entregado por el área de Compras
// (hojas SUPERVISORES y UNIDADES). Contiene los códigos oficiales de SAP para
// Unidad de Negocio, Cliente y Contrato, y el mapeo de Centro de Trabajo ->
// Cliente / Contrato / Unidad de Negocio / Proyecto / Sucursal que alimenta el
// autollenado de "Nueva Solicitud" y la exportación a SAP (ver sap-export.ts).
//
// Para actualizar: reemplazar estos arreglos cuando el área de Compras entregue
// un nuevo maestro de SAP. No editar los códigos a mano — deben coincidir
// exactamente con SAP Business One.

export interface CatalogoItem {
  codigo: string;
  nombre: string;
}

export interface SupervisorAsignacion {
  cedula: string;
  nombre: string;
  centroTrabajo: string;
  cliente: string;
  contrato: string;
  unidadNegocio: string;
  proyecto: string;
  sucursal: string;
}

// Catálogo de Unidades de Negocio (Norma de reparto) — SAP
export const UNIDADES_NEGOCIO: CatalogoItem[] = [
  { codigo: "DP000", nombre: "MISION" },
  { codigo: "DP001", nombre: "GERENCIA GENERAL" },
  { codigo: "DP002", nombre: "PLANEACIÓN ESTRATEGICA" },
  { codigo: "DP003", nombre: "GESTION HUMANA" },
  { codigo: "DP004", nombre: "GESTION DE CALIDAD" },
  { codigo: "DP005", nombre: "TIC´S" },
  { codigo: "DP006", nombre: "GERENCIA DE OPERACIONES" },
  { codigo: "DP007", nombre: "SELECCIÓN Y CONTRATACION" },
  { codigo: "DP008", nombre: "NOMINA" },
  { codigo: "DP009", nombre: "SEGURIDAD SOCIAL" },
  { codigo: "DP010", nombre: "SALUD Y SEGURIDAD EN EL TRABA" },
  { codigo: "DP011", nombre: "SERVICIO AL CLIENTE" },
  { codigo: "DP012", nombre: "GERENCIA COMERCIAL Y GESTORES" },
  { codigo: "DP013", nombre: "CONTABILIDAD" },
  { codigo: "DP014", nombre: "TESORERIA Y CARTERA" },
  { codigo: "DP015", nombre: "COMPRAS" },
  { codigo: "DP016", nombre: "ALMACEN" },
  { codigo: "DP017", nombre: "APRENDICES" },
  { codigo: "DP018", nombre: "REUBICADOS" },
  { codigo: "DP019", nombre: "INNOVACIÓN Y DESARROLLO" },
  { codigo: "DP020", nombre: "ADECUACIONES CASA INGENIO" },
  { codigo: "DP021", nombre: "CASA ADMINISTRATIVA AFRDU" },
  { codigo: "DP022", nombre: "PRESIDENCIA" },
  { codigo: "DP023", nombre: "FINCA CALIMA" },
  { codigo: "UN002", nombre: "SERVICIOS DE LOGÍSTICA" },
  { codigo: "UN003", nombre: "SERVICIOS DE ASEO" },
  { codigo: "UN004", nombre: "SERVICIOS DE MANTENIMIENTO" },
  { codigo: "UN006", nombre: "SERVICIOS GENERALES" },
  { codigo: "UN010", nombre: "PROCESOS DE SELECCIÓN" },
  { codigo: "UN011", nombre: "VISITAS DOMICILIARIAS" },
  { codigo: "UN013", nombre: "SERVICIO DE ADMINISTRACIÓN Y C" },
  { codigo: "UN014", nombre: "SERVICIO NOMINA" },
  { codigo: "UN015", nombre: "SERVICIO GESTION HUMANA" },
  { codigo: "UN016", nombre: "SERVI SEGURIDAD Y SALUD TRABAJ" },
  { codigo: "UN017", nombre: "SERVICIOS AGRICOLAS" },
  { codigo: "UN018", nombre: "OBRAS CIVILES" },
];

// Catálogo de Clientes — SAP
export const CLIENTES: CatalogoItem[] = [
  { codigo: "CL0006", nombre: "MENDIOLA SAS" },
  { codigo: "CL0013", nombre: "GOODYEAR" },
  { codigo: "CL0014", nombre: "INDEGA" },
  { codigo: "CL0015", nombre: "CELSIA DE COLOMBIA SA E.S.P" },
  { codigo: "CL0026", nombre: "PLASTICOS RIMAX SAS" },
  { codigo: "CL0031", nombre: "TUBOS DE OCCIDENTE S.A.S." },
  { codigo: "CL0033", nombre: "PLASTICOS ESPECIALES S.A.S." },
  { codigo: "CL0040", nombre: "COLOMBIANA DE MOLDEADOS S.A.S" },
  { codigo: "CL0043", nombre: "CCF FAMILIAR DEL VALLE DEL CAU" },
  { codigo: "CL0047", nombre: "EMBOHUILA" },
  { codigo: "CL0058", nombre: "FUNDAGOODYEAR" },
  { codigo: "CL0061", nombre: "ALUMINIO NACIONAL S.A." },
  { codigo: "CL0067", nombre: "CETSA" },
  { codigo: "CL0074", nombre: "INVER_SANTA_MONICA" },
  { codigo: "CL0087", nombre: "COMFANARINO" },
  { codigo: "CL01000", nombre: "SPIWAK COMPAÑIA EDIFICADORA S." },
  { codigo: "CL0130", nombre: "ALM GEN DE DEPOSIT ALMACAFE" },
  { codigo: "CL0134", nombre: "FEDECAFE" },
  { codigo: "CL0144", nombre: "MINISTERIO DEL TRABAJO" },
  { codigo: "CL0166", nombre: "FL_COLOMBIA_SAS" },
  { codigo: "CL0167", nombre: "DORRONSORO ELSA" },
  { codigo: "CL0171", nombre: "ALJURE RAIF" },
  { codigo: "CL0222", nombre: "PROSERVIS TEMPORALES SAS" },
  { codigo: "CL0233", nombre: "ERT ESP" },
  { codigo: "CL0238", nombre: "GARCES Y GOMEZ ING. LTDA" },
  { codigo: "CL0450", nombre: "MOLINO SANTA MARTA" },
  { codigo: "CL0493", nombre: "COORDINADORA MERCANTIL S.A." },
  { codigo: "CL0496", nombre: "SULFOQUIMICA S.A" },
  { codigo: "CL0497", nombre: "INTEGRANDO SAS" },
  { codigo: "CL0500", nombre: "DISTRIMOTOS S.A.S." },
  { codigo: "CL0531", nombre: "CRUZ ROJA COLOMB SEC VALLE" },
  { codigo: "CL0532", nombre: "AFEMVA" },
  { codigo: "CL0562", nombre: "LACASSINE SAS" },
  { codigo: "CL0563", nombre: "METECNO DE COLOMBIA SA" },
  { codigo: "CL0570", nombre: "REPONER SA" },
  { codigo: "CL0578", nombre: "CEMENTOS-SAN-MARCOS" },
  { codigo: "CL0593", nombre: "ADVANCE SCIENTIFIC DE COLOMBIA" },
  { codigo: "CL0599", nombre: "PRECISAGRO S.A.S" },
  { codigo: "CL0611", nombre: "PROMOCALI S.A. ESP" },
  { codigo: "CL0621", nombre: "ASOCIACION SINDICAL DE TRABAJA" },
  { codigo: "CL0625", nombre: "FALABAELLA DE COLOMBIA S.A." },
  { codigo: "CL0630", nombre: "ATENCOM" },
  { codigo: "CL0632", nombre: "INDUSTRIA CAFETERA DE NARIÑO S" },
  { codigo: "CL0637", nombre: "PG PROTECCION S.A SAS" },
  { codigo: "CL0641", nombre: "CORPORACION CLUB COLOMBIA" },
  { codigo: "CL0652", nombre: "TECNOQUIMICAS S.A." },
  { codigo: "CL0654", nombre: "SOCIEDAD COLEGIO CAMPESTRE ANG" },
  { codigo: "CL0663", nombre: "ARTEMISA S.A.S" },
  { codigo: "CL0665", nombre: "SAMALO S.A.S." },
  { codigo: "CL0669", nombre: "AUTOMUNDIAL S.A." },
  { codigo: "CL0680", nombre: "CENTRO ASEGURADOR DE PESADOS C" },
  { codigo: "CL0695", nombre: "MAYA GOMEZ LILIANA" },
  { codigo: "CL0699", nombre: "GESTION EMPRESARIAL & MEDIO AM" },
  { codigo: "CL0703", nombre: "ALJURE DEL CORRAL DACCACH SAS" },
  { codigo: "CL0711", nombre: "VICTORY ENTERPRISE S.A.S" },
  { codigo: "CL0720", nombre: "CONVERSIONES INDUSTRIALES RAYS" },
  { codigo: "CL0721", nombre: "MARCELO DUQUE OSPINA & ASOCIAD" },
  { codigo: "CL0731", nombre: "PG FORMAPLAX" },
  { codigo: "CL0733", nombre: "MAQUITE" },
  { codigo: "CL0738", nombre: "PG C.I DISEÑO Y MODA INTERNACI" },
  { codigo: "CL0739", nombre: "ALMACENES LA 14" },
  { codigo: "CL0740", nombre: "SERVICARE SAS" },
  { codigo: "CL0741", nombre: "GRUPO FALCON S.A. EN LIQUIDACI" },
  { codigo: "CL0742", nombre: "ASES DE COMPETENCIA Y CIA S.A." },
  { codigo: "CL0743", nombre: "BEATRIZ ELENA SALAZAR GOMEZ" },
  { codigo: "CL0745", nombre: "POLO INGENIERIA Y CONSTRUCCION" },
  { codigo: "CL0746", nombre: "PG CAJAS COLOMBIANAS S.A.S" },
  { codigo: "CL0747", nombre: "CARTONES DEL VALLE DEL CAUCA Y" },
  { codigo: "CL0749", nombre: "BANCO WWB S.A." },
  { codigo: "CL0752", nombre: "INSTITUTO PARA LA INVESTIGACIO" },
  { codigo: "CL0755", nombre: "TUBOSA S.A.S" },
  { codigo: "CL0756", nombre: "NUESTRA COOPERACTIVA ENTIDAD D" },
  { codigo: "CL0757", nombre: "CORPORACION DE EVENTOS Y FERIA" },
  { codigo: "CL0758", nombre: "FRANZUL S.A. EN LIQUIDACION" },
  { codigo: "CL0760", nombre: "VALLEJO MODA S.A.S." },
  { codigo: "CL0762", nombre: "BEST ONE SOLUCIONES TECNOLOGIC" },
  { codigo: "CL0765", nombre: "ESTRUMETAL S.A." },
  { codigo: "CL0766", nombre: "TIRADO ESCOBAR Y ABOGADOS S.A." },
  { codigo: "CL0767", nombre: "CIA DE CONTROL DE CONTAMINACIO" },
  { codigo: "CL0770", nombre: "ANFIBIA TRANSPORTES FLUVIAL" },
  { codigo: "CL0771", nombre: "C.I. GLOBAL COL" },
  { codigo: "CL0772", nombre: "AUTOPITS" },
  { codigo: "CL0773", nombre: "CALIMA MOTOR" },
  { codigo: "CL0774", nombre: "CIA. AUTOMOTRIZ DE OCC." },
  { codigo: "CL0775", nombre: "AUTOMOTORES DEL PACIF" },
  { codigo: "CL0777", nombre: "GRUPO UNIMIX" },
  { codigo: "CL0780", nombre: "LIDERAUTOS" },
  { codigo: "CL0784", nombre: "DISTRECE S.A." },
  { codigo: "CL0785", nombre: "CIA OPERADORA CLINICA HISP" },
  { codigo: "CL0787", nombre: "FERPLASTICOS S.A.S" },
  { codigo: "CL0789", nombre: "FOMENTO" },
  { codigo: "CL0790", nombre: "ESCALA" },
  { codigo: "CL0793", nombre: "GASTROENTEROLOGOS ASOCIAD SAS" },
  { codigo: "CL0794", nombre: "DIVERSIFICAR S.A." },
  { codigo: "CL0796", nombre: "LABORATORIOS EDO S.A.S" },
  { codigo: "CL0800", nombre: "FUNDACION ZOOLOGICA DE CALI" },
  { codigo: "CL0801", nombre: "ELSA DORRONSORO TENORIO Y CIA" },
  { codigo: "CL0802", nombre: "PG AGROGANADEROS DEL VALLE" },
  { codigo: "CL0803", nombre: "PG JHON FREYDER CHIMBACO CASTA" },
  { codigo: "CL0804", nombre: "D&L INMOBILIARIA Y ASESORIA JU" },
  { codigo: "CL0805", nombre: "FUNDEVAL" },
  { codigo: "CL0806", nombre: "PROMINENT COLOMBIA S A S" },
  { codigo: "CL0809", nombre: "GRUPO PREGIO S.A.S" },
  { codigo: "CL0815", nombre: "PG DISTRIBUIDORA NACIONAL COOP" },
  { codigo: "CL0818", nombre: "SUPERMASTICK SAS" },
  { codigo: "CL0819", nombre: "METRO COSTURA S.A.S" },
  { codigo: "CL0820", nombre: "FRANCISCO JAVIER RAMIREZ RAMIR" },
  { codigo: "CL0827", nombre: "MENOTTI Y CIA S.A.S" },
  { codigo: "CL0830", nombre: "CRECE HAIR CENTER S.A.S." },
  { codigo: "CL0831", nombre: "HYDROCARE S.A.S." },
  { codigo: "CL0832", nombre: "IMPORTADORA ANDINA DE REPUESTO" },
  { codigo: "CL0833", nombre: "PROMOAMBIENTAL DISTRITO SAS ES" },
  { codigo: "CL0834", nombre: "DON OCTAVIO S.A.S." },
  { codigo: "CL0836", nombre: "GLOBAL OIL LUBRICANTES SAS" },
  { codigo: "CL0837", nombre: "PALLOMARO S.A." },
  { codigo: "CL0839", nombre: "AGREGADOS Y MEZCLAS CACHIBI SA" },
  { codigo: "CL0840", nombre: "FAMOC DE PANEL" },
  { codigo: "CL0844", nombre: "PROCESADORA AVICOLA POLLO A S." },
  { codigo: "CL0847", nombre: "REDES LOGICAS LFC S.A.S" },
  { codigo: "CL0848", nombre: "BOTANIQUE S.A.S." },
  { codigo: "CL0849", nombre: "AMCOR FLEXIBLES CALI S.A.S." },
  { codigo: "CL0850", nombre: "NATURAL MEDY DISTRIBUCIONES S." },
  { codigo: "CL0852", nombre: "HOLLAND GROUP S.A.S" },
  { codigo: "CL0854", nombre: "TC BUEN S.A" },
  { codigo: "CL0856", nombre: "LA RECETA Y CIA S.A.S" },
  { codigo: "CL0857", nombre: "CENTRO COMERCIAL NOVACENTRO-PR" },
  { codigo: "CL0860", nombre: "AV INGINIERIA  S.A.S" },
  { codigo: "CL0862", nombre: "TRANSPORTES ATLAS LTDA. TRANSA" },
  { codigo: "CL0867", nombre: "PAMPA LTDA" },
  { codigo: "CL0870", nombre: "PG VELAR LTDA" },
  { codigo: "CL0871", nombre: "EMBOTELLADORA DE BEBIDAS DEL T" },
  { codigo: "CL0872", nombre: "GRUPO RENTALIFT S.A.S" },
  { codigo: "CL0873", nombre: "COATEREX S.A.S" },
  { codigo: "CL0874", nombre: "FOGEL ANDINA SAS" },
  { codigo: "CL0875", nombre: "AGENCIA DE SEGURO CM2" },
  { codigo: "CL0876", nombre: "TECOLSOFT INTEGRADORA DE SOLUC" },
  { codigo: "CL0877", nombre: "COMUNIIDAD EDUCATIVA IGUAZU S." },
  { codigo: "CL0878", nombre: "PG FRB FUNDACION ANTONIO RESTR" },
  { codigo: "CL0880", nombre: "PG TELEPERFORMANCE COLOMBIA S." },
  { codigo: "CL0882", nombre: "PG CAMARA DE COMERCIO DE CALI" },
  { codigo: "CL0884", nombre: "PG MARIO GERMAN CAMPO ABADIA" },
  { codigo: "CL0885", nombre: "PG DURAN CASTRO & CIA S.C.A AG" },
  { codigo: "CL0887", nombre: "AC EQUIPOS VALLE SAS" },
  { codigo: "CL0889", nombre: "AGRICOLA AUTOMOTRIZ S.A.S" },
  { codigo: "CL0894", nombre: "TOOLMATE DE COLOMBIA S.A.S." },
  { codigo: "CL0895", nombre: "PG INVERSIONES GAC S.A.S" },
  { codigo: "CL0896", nombre: "ASOCIACION COLOMBIANA DE TECNI" },
  { codigo: "CL0901", nombre: "DNA DISTRINAL S.A.S." },
  { codigo: "CL0903", nombre: "PG SSANGYONG MOTOR COLOMBIA S" },
  { codigo: "CL0906", nombre: "FRUTICOLA DE COLOMBIA SAS" },
  { codigo: "CL0908", nombre: "FIDUCIARIA POPULAR SA" },
  { codigo: "CL0909", nombre: "PATRIMONIOS AUTONOMOS FIDUCIAR" },
  { codigo: "CL0910", nombre: "SERVICIOS INDUSTRIALES Y PORTU" },
  { codigo: "CL0911", nombre: "PG INVERSIONES SALAS HERNANDEZ" },
  { codigo: "CL0912", nombre: "BELLINI ANGEL ASESORES DE SEGU" },
  { codigo: "CL0913", nombre: "REVLOG SAS" },
  { codigo: "CL0914", nombre: "PG MERQUIMIA INTERNACIONAL SAS" },
  { codigo: "CL0915", nombre: "SOFTWARE CAD CAM SAS" },
  { codigo: "CL0916", nombre: "UP EQUIPMENT S.A.S" },
  { codigo: "CL0917", nombre: "UPS ALFATEC SOPORTE Y TECNOLOG" },
  { codigo: "CL0918", nombre: "COLECTA SAS" },
  { codigo: "CL0919", nombre: "INVERCOOB COOPERATIVA DE AHOR" },
  { codigo: "CL0920", nombre: "SKEMA PROMOTORA S.A." },
  { codigo: "CL0921", nombre: "M&M DESIGN AND DEVELOPMENT S.A" },
  { codigo: "CL0922", nombre: "AGP DE COLOMBIA SA" },
  { codigo: "CL0923", nombre: "FRAGAROMA SAS" },
  { codigo: "CL0924", nombre: "SUKIPARTES S.A.S" },
  { codigo: "CL0925", nombre: "FUNDACIÓN DELAMUJER COLOMBIA S" },
  { codigo: "CL0926", nombre: "GABANA INVERSIONES S.A.S." },
  { codigo: "CL0927", nombre: "CENTRAL COLOMBIANA DE ASEO SA" },
  { codigo: "CL0928", nombre: "BRILLADORA EL DIAMANTE SA" },
  { codigo: "CL0929", nombre: "PLEXO SAS" },
  { codigo: "CL0930", nombre: "LEADTECH INNOVATION SLU" },
  { codigo: "CL0931", nombre: "APM CALI SAS" },
  { codigo: "CL0932", nombre: "JHL TRANS LOGISTICS S.A.S." },
  { codigo: "CL0933", nombre: "METALES Y MADERAS DEL RISARALD" },
  { codigo: "CL0934", nombre: "EPIK ASOCIADOS SAS" },
  { codigo: "CL0935", nombre: "I4 COLOMBIA S.A.S." },
  { codigo: "CL0936", nombre: "POLIETILENOS DEL VALLE S.A." },
  { codigo: "CL0937", nombre: "DIATREA S.A.S" },
  { codigo: "CL0938", nombre: "PRACTICOS S.A.S" },
  { codigo: "CL0939", nombre: "MESSIS S.A.S" },
  { codigo: "CL0940", nombre: "INDUMETAN SAS" },
  { codigo: "CL0941", nombre: "ESTRATEGIA EMPRESARIAL A.G  S." },
  { codigo: "CL0942", nombre: "CARLOS ALBERTO GIRALDO SALAZAR" },
  { codigo: "CL0943", nombre: "AUTOCENTRO CAPRI S.A" },
  { codigo: "CL0944", nombre: "SPECTRA INGENIERÍA SAS" },
  { codigo: "CL0945", nombre: "FONDO DE EMPLEADOS DEL DEPARTA" },
  { codigo: "CL0946", nombre: "INDUSTRIA DE MARGARINAS Y ACEI" },
  { codigo: "CL0947", nombre: "EUREKA AGRO S.A.S" },
  { codigo: "CL0948", nombre: "LIPU & CIA S.C.A" },
  { codigo: "CL0949", nombre: "COMERQUIAGUAS S.A.S." },
  { codigo: "CL0950", nombre: "VELHUR SAS" },
  { codigo: "CL0951", nombre: "TECNISOLUTIONS S.A.S." },
  { codigo: "CL0952", nombre: "PINO ECHAVARRIA DIEGO LEON" },
  { codigo: "CL0953", nombre: "BANDAS Y CORREAS INDUSTRIALES" },
  { codigo: "CL0954", nombre: "D+D CONSTRUCTORES S.A.S." },
  { codigo: "CL0955", nombre: "WILSON LEON LESMES" },
  { codigo: "CL0956", nombre: "DISTRIBUIDOR DE PAPELERIA LOS" },
  { codigo: "CL0957", nombre: "GAME S.A.S." },
  { codigo: "CL0958", nombre: "CLINICA FIORE S.A." },
  { codigo: "CL1000", nombre: "SPIWAK COMPAÑIA EDIFICADORA SA" },
  { codigo: "CL1001", nombre: "TORRE AGENCIA DE SEGUROS E IN" },
  { codigo: "CL1002", nombre: "FAREVA VILLA RICA S.A.S" },
  { codigo: "CL1003", nombre: "TRANSPORTES CENTRO VALLE S.A." },
  { codigo: "CL1004", nombre: "CETNI S.A.S" },
  { codigo: "CL1005", nombre: "INGENIO PICHICHI S.A." },
  { codigo: "CL1006", nombre: "NEGOCIOS E INMOBILIARIA CORDIL" },
  { codigo: "CL1008", nombre: "RIOPAILA CASTILLA S.A" },
  { codigo: "CL1010", nombre: "LEXCO S.A" },
  { codigo: "CL1011", nombre: "PARK 5 VALLE SAS" },
  { codigo: "CL1012", nombre: "UNISA UNION INMOBILIARIA S.A." },
  { codigo: "CL1013", nombre: "ROMANO GERMAN BARNEY DURAN" },
  { codigo: "CL1014", nombre: "NEGOCIOS BARNEY S.A.S" },
  { codigo: "CL1015", nombre: "CATALINA DIXON CARVAJAL" },
  { codigo: "CL1016", nombre: "LA RECETA Y CIA S.A.S." },
  { codigo: "CL1017", nombre: "JORGE CLAVIJO" },
  { codigo: "CL1019", nombre: "UNIVERSIDAD DEL VALLE" },
  { codigo: "CL1020", nombre: "INMOVILIAGRO S.A.S" },
  { codigo: "CL1021", nombre: "SERVIAGRICOLA MENDEZ LTDA" },
  { codigo: "CL1027", nombre: "AFFINE S.A.S" },
  { codigo: "CL1029", nombre: "CENTRO INTERNACIONAL DE AGRICU" },
  { codigo: "CL1030", nombre: "SANIMAX DE COLOMBIA S.A.S" },
  { codigo: "CL1031", nombre: "GRUPO LUZ Y FUERZA COLOMBIA S." },
  { codigo: "N0740202", nombre: "PG SERVICARE NM" },
  { codigo: "N076020", nombre: "PG VALLEJO MODA S.A.S." },
  { codigo: "N091220", nombre: "BELLINI ANGEL ASESORES DE SEGU" },
  { codigo: "PL0001", nombre: "ADMINISTRATIVO" },
  { codigo: "PL0002", nombre: "OPERACIÓN" },
  { codigo: "PL0004", nombre: "SENA" },
  { codigo: "PL0005", nombre: "VENTAS" },
  { codigo: "PL0006", nombre: "SERVICIOS AGRICOLA" },
  { codigo: "PL0015", nombre: "CELSIA DE COLOMBIA SA E.S.P" },
  { codigo: "PL006", nombre: "MENDIOLA" },
  { codigo: "PL0796", nombre: "LABORATORIO EDO" },
  { codigo: "PL0854", nombre: "TC BUEN S.A" },
];

// Catálogo de Contratos / Centros de costo — SAP
export const CONTRATOS: CatalogoItem[] = [
  { codigo: "BU024381", nombre: "COMFANDI" },
  { codigo: "DP0001", nombre: "GERENCIA GENERAL" },
  { codigo: "DP0002", nombre: "GERENCIA COMERCIAL" },
  { codigo: "DP0003", nombre: "GERENCIA ADMINISTRATIVA/ FINA" },
  { codigo: "DP0004", nombre: "GERENCIA DE OPERACIONES" },
  { codigo: "DP0005", nombre: "GERENCIA DE PLANEACION" },
  { codigo: "DQ058641", nombre: "BOTERO VELEZ Y CIA" },
  { codigo: "N0006201", nombre: "MENDIOLA SAS" },
  { codigo: "N0006202", nombre: "PG AGRICOLAS" },
  { codigo: "N0013201", nombre: "PG GOODYEAR ASEO Y MANTENIMIE" },
  { codigo: "N0013202", nombre: "PG GOODYEAR COMERCIAL" },
  { codigo: "N0013203", nombre: "PG GOODYEAR ADMINISTRATIVO, P" },
  { codigo: "N0014201", nombre: "PG INDEGA REPROCESOS" },
  { codigo: "N0014202", nombre: "PG INDEGA LAVADO DE CAMIONES" },
  { codigo: "N0014203", nombre: "PG INDEGA PICKING" },
  { codigo: "N0014204", nombre: "PG INDEGA FLETEO" },
  { codigo: "N0014205", nombre: "PG INDEGA MANUFACTURA" },
  { codigo: "N0014206", nombre: "PG INDEGA COMERCIAL" },
  { codigo: "N0014207", nombre: "PG INDEGA MERCADEO" },
  { codigo: "N0014208", nombre: "PG OPERACIÓN LOGÍSTICA INDEGA" },
  { codigo: "N0015202", nombre: "PG EPSA ASEO Y COMPLEMENTARIO" },
  { codigo: "N0015204", nombre: "PG EPSA MTTO CERROS Y SEDES" },
  { codigo: "N0015207", nombre: "PG EPSA EDUCACION" },
  { codigo: "N0015208", nombre: "PG EPSA OPERACION EMBALSE" },
  { codigo: "N0015209", nombre: "PG CELSIA Y JARDINERIA" },
  { codigo: "N0015210", nombre: "PG CELSIA PALERMO" },
  { codigo: "N0015212", nombre: "PODA CELSIA" },
  { codigo: "N0026201", nombre: "PG PLASTICOS RIMAX SAS" },
  { codigo: "N0031201", nombre: "PG TUBOS DE OCCIDENTE S.A.S." },
  { codigo: "N0033201", nombre: "PG PLASTICOS ESPECIALES S.A.S" },
  { codigo: "N0040201", nombre: "PG COLOMBIANA DE MOLDEADOS S." },
  { codigo: "N0047201", nombre: "PG EMBOHUILA" },
  { codigo: "N0058201", nombre: "PG FUNDAGOODYEAR" },
  { codigo: "N0061201", nombre: "PG ALUMINA" },
  { codigo: "N006202", nombre: "PG SERVICIOS AGRICOLAS" },
  { codigo: "N0067201", nombre: "PG CETSA" },
  { codigo: "N0074201", nombre: "PG INVER_SANTA_MONICA" },
  { codigo: "N0087201", nombre: "PG COMFANARINO" },
  { codigo: "N0134201", nombre: "PG FEDECAFE" },
  { codigo: "N0144201", nombre: "PG MINISTERIO DEL TRABAJO" },
  { codigo: "N0166201", nombre: "PG FL_COLOMBIA_SAS" },
  { codigo: "N0167201", nombre: "PG DORRONSORO ELSA" },
  { codigo: "N0171201", nombre: "PG ALJURE RAIF" },
  { codigo: "N0222201", nombre: "PG PROSERVIS TEMPORALES" },
  { codigo: "N023310", nombre: "ERT ESP" },
  { codigo: "N0233102", nombre: "PG ERT" },
  { codigo: "N0238201", nombre: "PG GARCES Y GOMEZ ING" },
  { codigo: "N0450201", nombre: "PG MOLINO-SANTA-MARTA" },
  { codigo: "N0493201", nombre: "PG COORDINADORA MERCANTIL S.A." },
  { codigo: "N0496102", nombre: "PG SULFOQUIMICA S.A" },
  { codigo: "N0497201", nombre: "PG  INTEGRANDO LTDA" },
  { codigo: "N0500201", nombre: "DISTRIMOTOS S.A.S." },
  { codigo: "N0531201", nombre: "PG CRUZ_ROJA_SEC_VALLE" },
  { codigo: "N0532201", nombre: "PG AFEMVA" },
  { codigo: "N0563201", nombre: "PG METECNO DE COLOMBIA SA" },
  { codigo: "N0570201", nombre: "REPONER SA" },
  { codigo: "N0578201", nombre: "PG CEMENTOS-SAN-MARCOS" },
  { codigo: "N0593201", nombre: "N0593201 - PG ADVANCE SCIENTIF" },
  { codigo: "N0599201", nombre: "PRECISAGRO S.A.S." },
  { codigo: "N0611201", nombre: "PG PROMOCALI S.A. ESP" },
  { codigo: "N0621201", nombre: "PG ASSTRACUD QUERYX" },
  { codigo: "N062520", nombre: "FALABELLA S.A." },
  { codigo: "N0625201", nombre: "FALABELLA S.A." },
  { codigo: "N0630201", nombre: "PG ATENCOM REPROCESOS" },
  { codigo: "N0630202", nombre: "PG ATENCOM LAVADO DE CAMIONES" },
  { codigo: "N0630203", nombre: "PG ATENCOM PICKING" },
  { codigo: "N0630204", nombre: "PG ATENCOM FLETEO" },
  { codigo: "N0630205", nombre: "PG ATENCOM MANUFACTURA" },
  { codigo: "N0630206", nombre: "PG ATENCOM COMERCIAL" },
  { codigo: "N0630207", nombre: "PG ATENCOM MERCADEO" },
  { codigo: "N0632102", nombre: "INDUSTRIA CAFETERA DE NARIÑO S" },
  { codigo: "N0637102", nombre: "PG PROTECCION S.A (SRV 19%)" },
  { codigo: "N0652201", nombre: "PG TECNOQUIMICAS" },
  { codigo: "N0654201", nombre: "PG COLEGIO ANGLO HISPANO" },
  { codigo: "N0663201", nombre: "PG ARTEMISA S.A.S." },
  { codigo: "N0665201", nombre: "PG SAMALO" },
  { codigo: "N0669201", nombre: "PG AUTOMUNDIAL S.A." },
  { codigo: "N0680201", nombre: "PG CENTRO ASEGURADOR DE PESADO" },
  { codigo: "N0695201", nombre: "PG MAYA GOMEZ LILIANA" },
  { codigo: "N0699201", nombre: "PG GESTION EMPRESARIAL & MEDIO" },
  { codigo: "N0703201", nombre: "PG ALJURE DEL CORRAL DACCACH" },
  { codigo: "N0711201", nombre: "PG VICTORY ENTERPRISE S.A.S" },
  { codigo: "N0720201", nombre: "PG CONVERSIONES INDUSTRIALES" },
  { codigo: "N0721201", nombre: "PG MARCELO DUQUE OSPINA Y ASO" },
  { codigo: "N073120", nombre: "PG FORMAPLAX" },
  { codigo: "N0733201", nombre: "PG MAQUITE" },
  { codigo: "N0738102", nombre: "PG C.I DISEÑO Y MODA INTERNACI" },
  { codigo: "N0739201", nombre: "PG ALMACENES LA 14" },
  { codigo: "N0740201", nombre: "PG SERVICARE" },
  { codigo: "N0741201", nombre: "PG GRUPO FALCON" },
  { codigo: "N0742201", nombre: "ASES DE COMPETENCIA" },
  { codigo: "N0743201", nombre: "PG BEATRIZ ELENA SALAZAR GOMEZ" },
  { codigo: "N0745201", nombre: "PG POLO INGENIERIA Y CONSTRUCC" },
  { codigo: "N0746102", nombre: "PG CAJAS COLOMBIANAS S.A.S" },
  { codigo: "N0747102", nombre: "CARTONES DEL VALLE DEL CAUCA Y" },
  { codigo: "N0749201", nombre: "PG BANCO WWB RECAUDO" },
  { codigo: "N0752201", nombre: "PG INCIVA" },
  { codigo: "N0755201", nombre: "PG LATINAMERICAN PIPES" },
  { codigo: "N0755202", nombre: "PG TUBOSA S.A.S" },
  { codigo: "N0756201", nombre: "PG COOPERACTIVA" },
  { codigo: "N0757201", nombre: "PG CORFECALI" },
  { codigo: "N0758201", nombre: "PG FRANZUL" },
  { codigo: "N0762201", nombre: "PG BEST ONE SOLUCIONES TECNOLO" },
  { codigo: "N0765201", nombre: "PG ESTRUMETAL S.A." },
  { codigo: "N0766201", nombre: "PG TIRADO ESCOBAR Y ABOGADOS S" },
  { codigo: "N0767201", nombre: "CIA DE CONTROL DE CONTAMINACIO" },
  { codigo: "N0770201", nombre: "PG PROSERVIS TRANSPORTES" },
  { codigo: "N0771201", nombre: "PG C.I. GLOBAL COL" },
  { codigo: "N0772201", nombre: "PG AUTOPITS" },
  { codigo: "N0773201", nombre: "PG CALIMA MOTOR" },
  { codigo: "N0774201", nombre: "PG CIA. AUTOMOTRIZ DE OCC." },
  { codigo: "N0775201", nombre: "PG AUTOMOTORES DEL PACIF" },
  { codigo: "N077720", nombre: "PG GRUPO UNIMIX" },
  { codigo: "N0780201", nombre: "PG LIDERAUTOS" },
  { codigo: "N0784201", nombre: "PG DISTRECE S.A" },
  { codigo: "N0785201", nombre: "PG CIA OPERADORA CLINICA HISP" },
  { codigo: "N0787201", nombre: "PG FERPLASTICOS S.A.S" },
  { codigo: "N0789201", nombre: "PG FOMENTO QUERYX" },
  { codigo: "N0790201", nombre: "PG ESCALA" },
  { codigo: "N0793201", nombre: "PG GASTROENTEROLOGOS ASOCIAD" },
  { codigo: "N0794201", nombre: "PG DIVERSIFICAR S.A." },
  { codigo: "N0796201", nombre: "PG LABORATORIOS EDO S.A.S" },
  { codigo: "N0800201", nombre: "PG FUNDACION ZOOLOGICA DE CALI" },
  { codigo: "N0801201", nombre: "PG ELSA DORRONSORO TENORIO Y C" },
  { codigo: "N0802201", nombre: "PG AGROGANADEROS DEL VALLE" },
  { codigo: "N0803201", nombre: "PG JHON FREYDER CHIMBACO CASTA" },
  { codigo: "N0804201", nombre: "PG D&L INMOBILIARIA Y ASESORIA" },
  { codigo: "N0805101", nombre: "PG FUNDEVAL" },
  { codigo: "N0806201", nombre: "PG PROMINENT COLOMBIA S A S" },
  { codigo: "N0809201", nombre: "PG GRUPO PREGIO S.A.S" },
  { codigo: "N0815102", nombre: "PG DISTRIBUIDORA NACIONAL COOP" },
  { codigo: "N0818201", nombre: "PG SUPERMASTICK" },
  { codigo: "N0819201", nombre: "PG METRO COSTURA" },
  { codigo: "N0820102", nombre: "PG OZONO FCO RAMIREZ" },
  { codigo: "N0827201", nombre: "PG MENOTTI" },
  { codigo: "N0830201", nombre: "PG CRECE HAIR CENTER" },
  { codigo: "N0831201", nombre: "PG HYDROCARE" },
  { codigo: "N0832201", nombre: "PG IMPORT ANDINA DE REPUESTOS" },
  { codigo: "N0833201", nombre: "PG PROMOAMBIENTAL DISTRITO" },
  { codigo: "N0834201", nombre: "PG DON OCTAVIO S.A.S." },
  { codigo: "N0836201", nombre: "PG GLOBAL OIL LUBRICANTES SAS" },
  { codigo: "N0837201", nombre: "PG PALLOMARO S.A." },
  { codigo: "N0839201", nombre: "PG CACHIBI  S.A" },
  { codigo: "N0840201", nombre: "PG FAMOC DE PANEL" },
  { codigo: "N0844201", nombre: "PG PROCESADORA AVICOLA POLLO" },
  { codigo: "N0847101", nombre: "PT REDES LOGICAS LFC S.A.S" },
  { codigo: "N0848201", nombre: "PG BOTANIQUE S.A.S" },
  { codigo: "N0849201", nombre: "AMCOR FLEXIBLES CALI S.A.S." },
  { codigo: "N0850201", nombre: "PG NATURAL MEDY DISTRIBUCIONES" },
  { codigo: "N0852201", nombre: "PG HOLLAND GROUP S.A.S" },
  { codigo: "N0854201", nombre: "PG T.C. BUEN S.A" },
  { codigo: "N0856201", nombre: "PG LA RECETA Y CIA S.A.S" },
  { codigo: "N0857201", nombre: "PG CENTRO COMERCIAL NOVACENTRO" },
  { codigo: "N0860201", nombre: "PG AV INGINIERIA  S.A.S" },
  { codigo: "N0862201", nombre: "PG TRANSP ATLAS LTDA TRANSATLA" },
  { codigo: "N0867201", nombre: "PG PAMPA LTDA" },
  { codigo: "N0870201", nombre: "PG VELAR LTDA" },
  { codigo: "N0871201", nombre: "EMBOTELLADORA DEL TOLIMA" },
  { codigo: "N0872102", nombre: "PG GRUPO RENTALIFT S.A.S" },
  { codigo: "N0873201", nombre: "PG COATEREX S.A.S" },
  { codigo: "N0874201", nombre: "PG FOGEL ANDINA SAS" },
  { codigo: "N0875201", nombre: "PG AGENCIA DE SEGURO CM2" },
  { codigo: "N0876201", nombre: "TECOLSOFT INTEGRADORA DE SOLUC" },
  { codigo: "N0877201", nombre: "PG COMUNIIDAD EDUCATIVA IGUAZU" },
  { codigo: "N0878201", nombre: "PG FRB FUNDACION ANTONIO RESTR" },
  { codigo: "N0880201", nombre: "PG TELEPERFORMANCE COLOMBIA S." },
  { codigo: "N0882201", nombre: "PG CAMARA DE COMERCIO DE CALI" },
  { codigo: "N0884201", nombre: "PG MARIO GERMAN CAMPO ABADIA" },
  { codigo: "N0885201", nombre: "PG DURAN CASTRO & CIA S.C.A AG" },
  { codigo: "N0887201", nombre: "PG AC EQUIPOS VALLE SAS" },
  { codigo: "N0889201", nombre: "AGRICOLA AUTOMOTRIZ S.A.S" },
  { codigo: "N0894201", nombre: "PG TOOLMATE DE COLOMBIA S.A.S" },
  { codigo: "N0895201", nombre: "PG INVERSIONES GAC S.A.S." },
  { codigo: "N0896201", nombre: "ASOCIACION COLOMBIANA DE TECNI" },
  { codigo: "N0901201", nombre: "PG DNA DISTRINAL S.A.S." },
  { codigo: "N0903102", nombre: "PG SSANGYONG MOTOR COLOMBIA S" },
  { codigo: "N090510", nombre: "CAJAS COLOMBIANAS S.A.S" },
  { codigo: "N0905102", nombre: "PG CAJAS COLOMBIANAS S.A.S" },
  { codigo: "N090620", nombre: "PG FRUTICOLA DE COLOMBIA SAS" },
  { codigo: "N0906201", nombre: "PG FRUTICOLA DE COLOMBIA SAS" },
  { codigo: "N0908201", nombre: "FIDUCIARIA POPULAR SA" },
  { codigo: "N0909201", nombre: "PATRIMONIOS AUTONOMOS FIDUCIAR" },
  { codigo: "N0910201", nombre: "SERVICIOS INDUSTRIALES Y PORTU" },
  { codigo: "N0911201", nombre: "PG INVERSIONES SALAS HERNANDEZ" },
  { codigo: "N0913201", nombre: "PG REVLOG SAS" },
  { codigo: "N0914201", nombre: "MERQUIMIA INTERNACIONAL SAS" },
  { codigo: "N0915201", nombre: "PG SOFTWARE CAD CAM SAS" },
  { codigo: "N0916201", nombre: "PG UP EQUIPMENT S.A.S." },
  { codigo: "N0917201", nombre: "PG UPS ALFATEC SOPORTE Y TECNO" },
  { codigo: "N0918201", nombre: "PG COLECTA SAS" },
  { codigo: "N0919201", nombre: "INVERCOOB COOPERATIVA DE AHOR" },
  { codigo: "N0920201", nombre: "SKEMA PROMOTORA S.A." },
  { codigo: "N0921201", nombre: "M&M DESIGN AND DEVELOPMENT S." },
  { codigo: "N0922201", nombre: "AGP DE COLOMBIA SA" },
  { codigo: "N0923201", nombre: "FRAGAROMA SAS" },
  { codigo: "N0924201", nombre: "SUKIPARTES S.A.S" },
  { codigo: "N0925201", nombre: "FUNDACIÓN DELAMUJER COLOMBIA S" },
  { codigo: "N0926201", nombre: "GABANA INVERSIONES S.A.S." },
  { codigo: "N0927201", nombre: "CENTRAL COLOMBIANA DE ASEO SA" },
  { codigo: "N0928201", nombre: "BRILLADORA EL DIAMANTE SA" },
  { codigo: "N0929201", nombre: "PLEXO SAS" },
  { codigo: "N0930201", nombre: "LEADTECH INNOVATION SLU" },
  { codigo: "N0931201", nombre: "APM CALI SAS" },
  { codigo: "N0932201", nombre: "JHL TRANS LOGISTICS S.A.S." },
  { codigo: "N0933201", nombre: "METALES Y MADERAS DEL RISARALD" },
  { codigo: "N0934201", nombre: "EPIK ASOCIADOS SAS" },
  { codigo: "N0935201", nombre: "I4 COLOMBIA S.A.S." },
  { codigo: "N0936201", nombre: "POLIETILENOS DEL VALLE S.A." },
  { codigo: "N0937201", nombre: "DIATREA S.A.S" },
  { codigo: "N0938201", nombre: "PRACTICOS S.A.S" },
  { codigo: "N0939201", nombre: "MESSIS S.A.S" },
  { codigo: "N0940201", nombre: "INDUMETAN SAS" },
  { codigo: "N0941201", nombre: "ESTRATEGIA EMPRESARIAL A.G  S" },
  { codigo: "N0942201", nombre: "CARLOS ALBERTO GIRALDO SALAZAR" },
  { codigo: "N0943201", nombre: "AUTOCENTRO CAPRI S.A" },
  { codigo: "N0944201", nombre: "SPECTRA INGENIERÍA SAS" },
  { codigo: "N0945201", nombre: "FONDO DE EMPLEADOS DEL DEPART" },
  { codigo: "N094620", nombre: "INDUSTRIA DE MARGARINAS Y ACEI" },
  { codigo: "N0947201", nombre: "EUREKA AGRO S.A.S" },
  { codigo: "N0948201", nombre: "LIPU & CIA S.C.A" },
  { codigo: "N0949201", nombre: "COMERQUIAGUAS S.A.S." },
  { codigo: "N0950201", nombre: "VELHUR SAS" },
  { codigo: "N0951201", nombre: "TECNISOLUTIONS S.A.S." },
  { codigo: "N0952201", nombre: "PINO ECHAVARRIA DIEGO LEON" },
  { codigo: "N0953201", nombre: "BANDAS Y CORREAS INDUSTRIALES" },
  { codigo: "N0954201", nombre: "D+D CONSTRUCTORES S.A.S." },
  { codigo: "N0955201", nombre: "WILSON LEON LESMES" },
  { codigo: "N0956201", nombre: "DISTRIBUIDOR DE PAPELERIA LOS" },
  { codigo: "N0957201", nombre: "GAME S.A.S" },
  { codigo: "N0958201", nombre: "CLINICA FIORE S.A" },
  { codigo: "N1000201", nombre: "SPIWAK COMPAÑIA EDIFICADORA SA" },
  { codigo: "N1001201", nombre: "DE LA TORRE AGENCIA DE SEGUROS" },
  { codigo: "N1002201", nombre: "FAREVA VILLA RICA S.A.S" },
  { codigo: "N100320", nombre: "TRANSPORTES CENTRO VALLE S.A." },
  { codigo: "N1004201", nombre: "CETNI S.A.S" },
  { codigo: "N1005201", nombre: "INGENIO PICHICHI S.A." },
  { codigo: "N1006201", nombre: "NEGOCIOS E INMOBILIARIA CORDIL" },
  { codigo: "N1008201", nombre: "RIOPAILA CASTILLA S.A" },
  { codigo: "N1008202", nombre: "TRACTORES OFICIOS VARIOS" },
  { codigo: "N1008203", nombre: "LAGUNA" },
  { codigo: "N1010201", nombre: "LEXCO S.A" },
  { codigo: "N101120", nombre: "PARK 5 VALLE SAS" },
  { codigo: "N1011201", nombre: "PARK 5 VALLE SAS" },
  { codigo: "N1012201", nombre: "UNISA UNION INMOBILIARIA S.A." },
  { codigo: "N1013201", nombre: "ROMANO GERMAN BARNEY DURAN" },
  { codigo: "N1014201", nombre: "NEGOCIOS BARNEY S.A.S." },
  { codigo: "N1015201", nombre: "CATALINA DIXON CARVAJAL" },
  { codigo: "N1016201", nombre: "LA RECETA Y CIA S.A.S" },
  { codigo: "N1017201", nombre: "JORGE CLAVIJO" },
  { codigo: "N1019201", nombre: "UNIVERSIDAD DEL VALLE" },
  { codigo: "N1019202", nombre: "SERVICIO DE ASEO UNIVALLE" },
  { codigo: "N1020201", nombre: "INMOVILIAGRO S.A.S" },
  { codigo: "N102120", nombre: "SERVIAGRICOLA MENDEZ LTDA" },
  { codigo: "N1021201", nombre: "SERVIAGRICOLA MENDEZ LTDA" },
  { codigo: "N1027201", nombre: "AFFINE S.A.S" },
  { codigo: "N1029201", nombre: "CENTRO INTERNACIONAL DE AGRICU" },
  { codigo: "N1030201", nombre: "SANIMAX DE COLOMBIA S.A.S" },
  { codigo: "N1031201", nombre: "GRUPO LUZ Y FUERZA COLOMBIA S." },
  { codigo: "PL015", nombre: "PL015" },
  { codigo: "PT034151", nombre: "ALMACAFE" },
  { codigo: "PT038801", nombre: "CLUB COLOMBIA PG" },
  { codigo: "UN0054", nombre: "UN0054" },
  { codigo: "YU113023", nombre: "EPSA OPRACION MTTO BAJO" },
];

// Mapeo real Centro de Trabajo -> datos SAP, tomado de la hoja SUPERVISORES.
// Se usa como catálogo de referencia para el autollenado y para pre-cargar
// la plantilla de "Carga Masiva" de Asignaciones (admin > Asignaciones).
// NOTA: un mismo supervisor puede tener varios centros de trabajo asignados.
export const SUPERVISORES_SIAMO: SupervisorAsignacion[] = [
  { cedula: "1004573250", nombre: "MANCILLA ALDERETI EYDER EVELIO", centroTrabajo: "SALVAJINA", cliente: "CL0015", contrato: "N0015209", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1004573250", nombre: "MANCILLA ALDERETI EYDER EVELIO", centroTrabajo: "UNIVALLE", cliente: "CL1019", contrato: "N1019202", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1112472573", nombre: "PABON JIMENEZ MAURICIO", centroTrabajo: "PLANTAS MENORES", cliente: "CL0015", contrato: "N0015209", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1112472573", nombre: "PABON JIMENEZ MAURICIO", centroTrabajo: "GLF", cliente: "CL1031", contrato: "N1031201", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1006233801", nombre: "SOLORZANO LONDOÑO STEPHANIA", centroTrabajo: "INDEGA", cliente: "CL0014", contrato: "N0014208", unidadNegocio: "UN002", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1144040468", nombre: "VASQUEZ QUINTERO DIANA CAROLINA", centroTrabajo: "INDEGA", cliente: "CL0014", contrato: "N0014208", unidadNegocio: "UN002", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "4512400", nombre: "ACOSTA BURITICA FERNANDO", centroTrabajo: "INDEGA", cliente: "CL0014", contrato: "N0014208", unidadNegocio: "UN002", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "28880879", nombre: "YARA AMAYA ADRIANA LORENA", centroTrabajo: "PRADO", cliente: "CL0015", contrato: "N0015209", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "28880879", nombre: "YARA AMAYA ADRIANA LORENA", centroTrabajo: "CUCUANA", cliente: "CL0015", contrato: "N0015209", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1113515547", nombre: "ESCOBAR CARDONA YEISON ARTURO", centroTrabajo: "CIAT", cliente: "CL1029", contrato: "N1029201", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1144194233", nombre: "CLEVEL ANGULO JESUS ALBERTO", centroTrabajo: "SANIMAX-AMAGA", cliente: "CL1030", contrato: "N1030201", unidadNegocio: "UN002", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1144194233", nombre: "CLEVEL ANGULO JESUS ALBERTO", centroTrabajo: "SANIMAX-SIBATE", cliente: "CL1030", contrato: "N1030201", unidadNegocio: "UN002", proyecto: "SIAMO", sucursal: "SC001" },
  { cedula: "1112878557", nombre: "MARIN CAMPO JOSE CAMILO", centroTrabajo: "CALIMA", cliente: "CL0015", contrato: "N0015209", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC002" },
  { cedula: "1112878557", nombre: "MARIN CAMPO JOSE CAMILO", centroTrabajo: "PALERMO", cliente: "CL0015", contrato: "N0015210", unidadNegocio: "UN006", proyecto: "SIAMO", sucursal: "SC003" },
];


// ─── HELPERS DE BÚSQUEDA ──────────────────────────────────

function buscarNombre(catalogo: CatalogoItem[], codigo: string): string {
  const item = catalogo.find(c => c.codigo === codigo);
  return item?.nombre || '';
}

export const nombreUnidadNegocio = (codigo: string) => buscarNombre(UNIDADES_NEGOCIO, codigo);
export const nombreCliente = (codigo: string) => buscarNombre(CLIENTES, codigo);
export const nombreContrato = (codigo: string) => buscarNombre(CONTRATOS, codigo);

// Datos SAP (cliente/contrato/unidadNegocio/proyecto/sucursal) para un Centro de
// Trabajo dado, tomados de SUPERVISORES_SIAMO. Si el mismo centro aparece con
// varios supervisores se usa el primero encontrado.
export function datosSapPorCentroTrabajo(centroTrabajo: string): Omit<SupervisorAsignacion, 'cedula' | 'nombre' | 'centroTrabajo'> | null {
  const match = SUPERVISORES_SIAMO.find(
    s => s.centroTrabajo.trim().toLowerCase() === centroTrabajo.trim().toLowerCase()
  );
  if (!match) return null;
  return {
    cliente: match.cliente,
    contrato: match.contrato,
    unidadNegocio: match.unidadNegocio,
    proyecto: match.proyecto,
    sucursal: match.sucursal,
  };
}

// Lista de centros de trabajo únicos conocidos (para autocompletar / sugerencias).
export const CENTROS_TRABAJO_CONOCIDOS: string[] = [...new Set(SUPERVISORES_SIAMO.map(s => s.centroTrabajo))];
